name: Pull Request validation

on: 
  pull_request:
    branches:
      - main
  schedule:
    - cron: "0 8 * * 1" # Each monday 8 AM UTC

jobs:
  pr-check:
    name: Check Python
    uses: ./.github/workflows/check-python.yaml
