[project]
name = "starter_python"
version = "0.1.0"
description = "Algorand smart contracts"
readme = "README.md"
requires-python = ">=3.12,<3.14"
dependencies = [
  "algokit-utils>=5.0.0a13",
  "python-dotenv>=1.0.0",
  "algorand-python>=3",
  "algorand-python-testing @ git+https://github.com/algorandfoundation/algorand-python-testing.git@refactor/util-v5",
]

[dependency-groups]
dev = [
"algokit-client-generator>=3.0.0a3",
"puyapy",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.metadata]
allow-direct-references = true

[tool.uv]
package = false

